/**
 * Generates `docs/REFERENCE.md` from the built type declarations.
 * `--check` fails when the checked-in output is stale rather than rewriting it.
 *
 * It reads `dist`, not the source, so the reference lists what a consumer can
 * actually import. A list of subpath names was not a reference — it could not
 * go stale in any way that mattered, so checking it proved nothing.
 */
import { join } from "node:path";
import { readFile, writeFile } from "node:fs/promises";

const root = join(import.meta.dir, "..");
const manifest = await Bun.file(join(root, "package.json")).json() as {
  exports: Record<string, { types?: string }>;
};

const label = (subpath: string) => `aglib${subpath === "." ? "" : subpath.slice(1)}`;

/**
 * Exported names from a declaration file.
 *
 * Deliberately textual. A type-aware pass would need the compiler API to say
 * something the source already says plainly, and the names are what a reference
 * is for — the signatures live one hover away.
 */
function exportedNames(declaration: string): string[] {
  const names = new Set<string>();
  const direct = /^export declare (?:function|const|class) (\w+)|^export (?:interface|type|enum) (\w+)/gm;
  for (const match of declaration.matchAll(direct)) names.add(match[1] ?? match[2]!);

  const listed = /^export(?: type)? \{([^}]*)\}/gm;
  for (const match of declaration.matchAll(listed)) {
    for (const part of match[1]!.split(",")) {
      const name = part.trim().split(/\s+as\s+/).pop()?.replace(/^type\s+/, "").trim();
      if (name) names.add(name);
    }
  }
  return [...names].sort((a, b) => a.localeCompare(b));
}

const sections: string[] = [];
for (const subpath of Object.keys(manifest.exports).sort()) {
  const types = manifest.exports[subpath]?.types;
  const declaration = types ? await readFile(join(root, types), "utf8").catch(() => "") : "";
  const names = exportedNames(declaration);
  sections.push(`### \`${label(subpath)}\``, "");
  sections.push(names.length ? names.map((name) => `\`${name}\``).join(" · ") : "_Nothing exported._");
  sections.push("");
}

const reference = [
  "# API reference",
  "",
  "> Generated by `bun run docs` from the built declarations. Do not edit by hand.",
  "",
  "Every name a consumer can import, by entry point. What each one means belongs to",
  "[`INTERFACE.md`](INTERFACE.md) and [`ARCHITECTURE.md`](ARCHITECTURE.md); this is the inventory.",
  "",
  ...sections,
].join("\n");

const target = join(root, "docs/REFERENCE.md");
const count = sections.filter((line) => line.startsWith("### ")).length;

if (process.argv.includes("--check")) {
  const current = await readFile(target, "utf8").catch(() => "");
  if (current !== reference) {
    console.error("docs/REFERENCE.md is stale — run `bun run docs`");
    process.exit(1);
  }
  console.log(`docs: ${count} entry points, reference is current`);
} else {
  await writeFile(target, reference);
  console.log(`docs: wrote ${count} entry points to docs/REFERENCE.md`);
}
